name: Sandbox Action

on:
  push
jobs: 
  sandbox:
    name: Sandbox Integration 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find joke.js
        run: find . -name "joke.js"
        
      - name: Print message
        run: echo "Hello World"
